# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1ae4292f545c59551c132298a5d26f62dc927a065b91be78da9401e5ac10cf9e02468fffe692d058b291b14a9e1281e8d02edbd2758100f1bf157fbf6a23d19

test:
  secret_key_base: 4f528b301ee0a5c017d0119792be1f7b094bb395222ee2eaeb540f20402ce53c263a5b17a032d4275406f4bbc1bab2144eb5bb9928566659d80c11a51d3b70a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
